const wines = [
  {
    id: 1,
    name: "Cabernet Sauvignon",
    type: "red",
    body: "full",
    tannin: "high",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["red meat", "steak", "lamb", "aged cheese", "grilled food"],
    region: "France",
    price: 28
  },
  {
    id: 2,
    name: "Merlot",
    type: "red",
    body: "medium",
    tannin: "medium",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["beef", "pasta", "mushrooms", "roast chicken"],
    region: "USA",
    price: 22
  },
  {
    id: 3,
    name: "Pinot Noir",
    type: "red",
    body: "light",
    tannin: "low",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["salmon", "duck", "mushrooms", "roast chicken"],
    region: "USA",
    price: 24
  },
  {
    id: 4,
    name: "Syrah",
    type: "red",
    body: "full",
    tannin: "high",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["bbq", "grilled meat", "lamb", "spicy food"],
    region: "Australia",
    price: 26
  },
  {
    id: 5,
    name: "Malbec",
    type: "red",
    body: "full",
    tannin: "medium",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["steak", "burger", "bbq", "hard cheese"],
    region: "Argentina",
    price: 21
  },
  {
    id: 6,
    name: "Chardonnay",
    type: "white",
    body: "medium",
    tannin: "low",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["chicken", "seafood", "creamy pasta", "lobster"],
    region: "France",
    price: 23
  },
  {
    id: 7,
    name: "Sauvignon Blanc",
    type: "white",
    body: "light",
    tannin: "low",
    acidity: "high",
    sweetness: "dry",
    pairings: ["salad", "goat cheese", "fish", "shellfish"],
    region: "New Zealand",
    price: 19
  },
  {
    id: 8,
    name: "Riesling",
    type: "white",
    body: "light",
    tannin: "low",
    acidity: "high",
    sweetness: "off-dry",
    pairings: ["spicy food", "thai", "indian", "pork"],
    region: "Germany",
    price: 18
  },
  {
    id: 9,
    name: "Pinot Grigio",
    type: "white",
    body: "light",
    tannin: "low",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["seafood", "salad", "light pasta"],
    region: "Italy",
    price: 17
  },
  {
    id: 10,
    name: "Gewürztraminer",
    type: "white",
    body: "medium",
    tannin: "low",
    acidity: "medium",
    sweetness: "off-dry",
    pairings: ["spicy food", "asian cuisine", "pork"],
    region: "France",
    price: 20
  },
  {
    id: 11,
    name: "Zinfandel",
    type: "red",
    body: "full",
    tannin: "medium",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["bbq", "pizza", "burger"],
    region: "USA",
    price: 25
  },
  {
    id: 12,
    name: "Chianti",
    type: "red",
    body: "medium",
    tannin: "medium",
    acidity: "high",
    sweetness: "dry",
    pairings: ["tomato pasta", "pizza", "italian food"],
    region: "Italy",
    price: 19
  },
  {
    id: 13,
    name: "Prosecco",
    type: "sparkling",
    body: "light",
    tannin: "low",
    acidity: "high",
    sweetness: "dry",
    pairings: ["appetizers", "seafood", "light snacks"],
    region: "Italy",
    price: 16
  },
  {
    id: 14,
    name: "Champagne",
    type: "sparkling",
    body: "light",
    tannin: "low",
    acidity: "high",
    sweetness: "dry",
    pairings: ["oysters", "seafood", "celebration dishes"],
    region: "France",
    price: 45
  },
  {
    id: 15,
    name: "Rosé",
    type: "rosé",
    body: "light",
    tannin: "low",
    acidity: "medium",
    sweetness: "dry",
    pairings: ["salad", "grilled vegetables", "light pasta"],
    region: "Spain",
    price: 18
  }
];

module.exports = wines;